using Microsoft.EntityFrameworkCore;
using EcommercePos.Domain.Entities;

namespace EcommercePos.Application.Common;

public interface IApplicationDbContext
{
    DbSet<ActivityLogs> ActivityLogs { get; set; }
    DbSet<AppSettings> AppSettings { get; set; }
    DbSet<AttributeOptionMedia> AttributeOptionMedia { get; set; }
    DbSet<AttributeOptionMediaBlob> AttributeOptionMediaBlob { get; set; }
    DbSet<AttributeOptions> AttributeOptions { get; set; }
    DbSet<AttributeTypes> AttributeTypes { get; set; }
    DbSet<AuditLogs> AuditLogs { get; set; }
    DbSet<BlogCategories> BlogCategories { get; set; }
    DbSet<BlogComments> BlogComments { get; set; }
    DbSet<BlogTags> BlogTags { get; set; }
    DbSet<Blogs> Blogs { get; set; }
    DbSet<Brands> Brands { get; set; }
    DbSet<BundleComponents> BundleComponents { get; set; }
    DbSet<BundleOptionGroups> BundleOptionGroups { get; set; }
    DbSet<BundleOptionItems> BundleOptionItems { get; set; }
    DbSet<CartItems> CartItems { get; set; }
    DbSet<Carts> Carts { get; set; }
    DbSet<CashDrawerEvents> CashDrawerEvents { get; set; }
    DbSet<CashShifts> CashShifts { get; set; }
    DbSet<Categories> Categories { get; set; }
    DbSet<Colors> Colors { get; set; }
    DbSet<ContactMessages> ContactMessages { get; set; }
    DbSet<Currencies> Currencies { get; set; }
    DbSet<CustomerAddresses> CustomerAddresses { get; set; }
    DbSet<CustomerProfiles> CustomerProfiles { get; set; }
    DbSet<CustomerTiers> CustomerTiers { get; set; }
    DbSet<CustomerWallets> CustomerWallets { get; set; }
    DbSet<Customers> Customers { get; set; }
    DbSet<DayEndSummaries> DayEndSummaries { get; set; }
    DbSet<DeliveryZoneRegions> DeliveryZoneRegions { get; set; }
    DbSet<DeliveryZones> DeliveryZones { get; set; }
    DbSet<DiscountApplicability> DiscountApplicability { get; set; }
    DbSet<DiscountTypes> DiscountTypes { get; set; }
    DbSet<DiscountUsageLog> DiscountUsageLog { get; set; }
    DbSet<Discounts> Discounts { get; set; }
    DbSet<EmailTemplates> EmailTemplates { get; set; }
    DbSet<Employees> Employees { get; set; }
    DbSet<ExpenseCategories> ExpenseCategories { get; set; }
    DbSet<Expenses> Expenses { get; set; }
    DbSet<FlashDealProducts> FlashDealProducts { get; set; }
    DbSet<FlashDeals> FlashDeals { get; set; }
    DbSet<GoodsReceiptLines> GoodsReceiptLines { get; set; }
    DbSet<GoodsReceipts> GoodsReceipts { get; set; }
    DbSet<InventoryAdjustmentLines> InventoryAdjustmentLines { get; set; }
    DbSet<InventoryAdjustments> InventoryAdjustments { get; set; }
    DbSet<Invoices> Invoices { get; set; }
    DbSet<LoyaltyTransactions> LoyaltyTransactions { get; set; }
    DbSet<MediaAssets> MediaAssets { get; set; }
    DbSet<Menus> Menus { get; set; }
    DbSet<NewsletterSubscribers> NewsletterSubscribers { get; set; }
    DbSet<Notifications> Notifications { get; set; }
    DbSet<OrderBundleSelections> OrderBundleSelections { get; set; }
    DbSet<OrderItemTaxes> OrderItemTaxes { get; set; }
    DbSet<OrderItems> OrderItems { get; set; }
    DbSet<OrderReturnItems> OrderReturnItems { get; set; }
    DbSet<OrderStatuses> OrderStatuses { get; set; }
    DbSet<Orders> Orders { get; set; }
    DbSet<PaymentGateways> PaymentGateways { get; set; }
    DbSet<PaymentMethods> PaymentMethods { get; set; }
    DbSet<PaymentStatuses> PaymentStatuses { get; set; }
    DbSet<Payments> Payments { get; set; }
    DbSet<Permissions> Permissions { get; set; }
    DbSet<PickupPoints> PickupPoints { get; set; }
    DbSet<PosCounters> PosCounters { get; set; }
    DbSet<PosPaymentTenders> PosPaymentTenders { get; set; }
    DbSet<PosTerminals> PosTerminals { get; set; }
    DbSet<PosTransactionBundleSelections> PosTransactionBundleSelections { get; set; }
    DbSet<PosTransactionLineTaxes> PosTransactionLineTaxes { get; set; }
    DbSet<PosTransactionLines> PosTransactionLines { get; set; }
    DbSet<PosTransactionReturnLines> PosTransactionReturnLines { get; set; }
    DbSet<PosTransactionReturns> PosTransactionReturns { get; set; }
    DbSet<PosTransactions> PosTransactions { get; set; }
    DbSet<PriceListItems> PriceListItems { get; set; }
    DbSet<PriceLists> PriceLists { get; set; }
    DbSet<ProductAttributeLinks> ProductAttributeLinks { get; set; }
    DbSet<ProductBatches> ProductBatches { get; set; }
    DbSet<ProductCollectionItems> ProductCollectionItems { get; set; }
    DbSet<ProductCollections> ProductCollections { get; set; }
    DbSet<ProductConditions> ProductConditions { get; set; }
    DbSet<ProductImages> ProductImages { get; set; }
    DbSet<ProductMedia> ProductMedia { get; set; }
    DbSet<ProductMediaBlob> ProductMediaBlob { get; set; }
    DbSet<ProductPriceHistories> ProductPriceHistories { get; set; }
    DbSet<ProductSpecificationValues> ProductSpecificationValues { get; set; }
    DbSet<ProductSpecifications> ProductSpecifications { get; set; }
    DbSet<ProductSupplierLinks> ProductSupplierLinks { get; set; }
    DbSet<ProductTags> ProductTags { get; set; }
    DbSet<ProductTaxRates> ProductTaxRates { get; set; }
    DbSet<ProductVariants> ProductVariants { get; set; }
    DbSet<Products> Products { get; set; }
    DbSet<PurchaseOrderLineTaxes> PurchaseOrderLineTaxes { get; set; }
    DbSet<PurchaseOrderLines> PurchaseOrderLines { get; set; }
    DbSet<PurchaseOrders> PurchaseOrders { get; set; }
    DbSet<PurchaseReturnLines> PurchaseReturnLines { get; set; }
    DbSet<PurchaseReturns> PurchaseReturns { get; set; }
    DbSet<QuoteItems> QuoteItems { get; set; }
    DbSet<Quotes> Quotes { get; set; }
    DbSet<RefundRequests> RefundRequests { get; set; }
    DbSet<ReorderRules> ReorderRules { get; set; }
    DbSet<ReturnStatuses> ReturnStatuses { get; set; }
    DbSet<Returns> Returns { get; set; }
    DbSet<ReviewHelpfulness> ReviewHelpfulness { get; set; }
    DbSet<Reviews> Reviews { get; set; }
    DbSet<RoleClaims> RoleClaims { get; set; }
    DbSet<RoleMenus> RoleMenus { get; set; }
    DbSet<RolePermissions> RolePermissions { get; set; }
    DbSet<Roles> Roles { get; set; }
    DbSet<SearchKeywords> SearchKeywords { get; set; }
    DbSet<Sellers> Sellers { get; set; }
    DbSet<ShipmentStatuses> ShipmentStatuses { get; set; }
    DbSet<Shipments> Shipments { get; set; }
    DbSet<ShippingCarriers> ShippingCarriers { get; set; }
    DbSet<ShippingMethods> ShippingMethods { get; set; }
    DbSet<StaticPages> StaticPages { get; set; }
    DbSet<StockItems> StockItems { get; set; }
    DbSet<StockMovementTypes> StockMovementTypes { get; set; }
    DbSet<StockMovements> StockMovements { get; set; }
    DbSet<StockTransferLines> StockTransferLines { get; set; }
    DbSet<StockTransfers> StockTransfers { get; set; }
    DbSet<Suppliers> Suppliers { get; set; }
    DbSet<SupportTicketMessages> SupportTicketMessages { get; set; }
    DbSet<SupportTickets> SupportTickets { get; set; }
    DbSet<Tags> Tags { get; set; }
    DbSet<TaxRates> TaxRates { get; set; }
    DbSet<Units> Units { get; set; }
    DbSet<UserClaims> UserClaims { get; set; }
    DbSet<UserLogins> UserLogins { get; set; }
    DbSet<UserRefreshTokens> UserRefreshTokens { get; set; }
    DbSet<UserRoles> UserRoles { get; set; }
    DbSet<UserTokens> UserTokens { get; set; }
    DbSet<Users> Users { get; set; }
    DbSet<VariantAttributeMatrix> VariantAttributeMatrix { get; set; }
    DbSet<VariantAttributeOptions> VariantAttributeOptions { get; set; }
    DbSet<VwCustomerLoyaltyBalance> VwCustomerLoyaltyBalance { get; set; }
    DbSet<VwCustomerStats> VwCustomerStats { get; set; }
    DbSet<VwProductStats> VwProductStats { get; set; }
    DbSet<VwStockAvailability> VwStockAvailability { get; set; }
    DbSet<WalletTransactions> WalletTransactions { get; set; }
    DbSet<Warehouses> Warehouses { get; set; }
    DbSet<WishlistItems> WishlistItems { get; set; }
    DbSet<WishlistTypes> WishlistTypes { get; set; }
    DbSet<Wishlists> Wishlists { get; set; }

    Task<int> SaveChangesAsync(CancellationToken cancellationToken = default);
}
